//
//  BPProfileModule.h
//  ReactNativeIOSLibrary
//
//  Created by daiqingquan on 2016/11/23.
//  Copyright © 2016年 daiqingquan. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "RCTBridgeModule.h"
@interface BPProfileModule : NSObject<RCTBridgeModule>

#define kACTION_ERROR_BP @"ACTION_ERROR_BP"
#define kACTION_BATTERY_BP @"ACTION_BATTERY_BP"
#define kACTION_ZOREING_BP @"ACTION_ZOREING_BP"
#define kACTION_ZOREOVER_BP @"ACTION_ZOREOVER_BP"
#define kACTION_ONLINE_PRESSURE_BP @"ACTION_ONLINE_PRESSURE_BP"
#define kACTION_ONLINE_PULSEWAVE_BP @"ACTION_ONLINE_PULSEWAVE_BP"
#define kACTION_ONLINE_RESULT_BP @"ACTION_ONLINE_RESULT_BP"
#define kACTION_HISTORICAL_NUM_BP @"ACTION_HISTORICAL_NUM_BP"
#define kACTION_HISTORICAL_DATA_BP @"ACTION_HISTORICAL_DATA_BP"
#define kACTION_HISTORICAL_OVER_BP @"ACTION_HISTORICAL_OVER_BP"
#define kACTION_FUNCTION_INFORMATION_BP @"ACTION_FUNCTION_INFORMATION_BP"
#define kACTION_SET_UNIT_SUCCESS_BP @"ACTION_SET_UNIT_SUCCESS_BP"
#define kACTION_SET_ANGLE_SUCCESS_BP @"ACTION_SET_ANGLE_SUCCESS_BP"
#define kACTION_INTERRUPTED_BP @"ACTION_INTERRUPTED_BP"

#define kACTION @"action"
#define kERROR_NUM_BP @"ERROR_NUM_BP"
#define kBATTERY_BP @"BATTERY_BP"
#define kBLOOD_PRESSURE_BP @"BLOOD_PRESSURE_BP"
#define kFLAG_HEARTBEAT_BP @"FLAG_HEARTBEAT_BP"
#define kPULSEWAVE_BP @"PULSEWAVE_BP"
#define kHIGH_BLOOD_PRESSURE_BP @"HIGH_BLOOD_PRESSURE_BP"
#define kLOW_BLOOD_PRESSURE_BP @"LOW_BLOOD_PRESSURE_BP"
#define kPULSE_BP @"PULSE_BP"
#define kMEASUREMENT_AHR_BP @"MEASUREMENT_AHR_BP"
#define kMEASUREMENT_HSD_BP @"MEASUREMENT_HSD_BP"
#define kDATAID @"DATAID"
#define kHISTORICAL_NUM_BP @"HISTORICAL_NUM_BP"
#define kHISTORICAL_DATA_BP @"HISTORICAL_DATA_BP"
#define kFUNCTION_IS_UPAIR_MEASURE @"FUNCTION_IS_UPAIR_MEASURE"
#define kFUNCTION_IS_ARM_MEASURE @"FUNCTION_IS_ARM_MEASURE"
#define kFUNCTION_HAVE_ANGLE_SENSOR @"FUNCTION_HAVE_ANGLE_SENSOR"
#define kFUNCTION_HAVE_OFFLINE @"FUNCTION_HAVE_OFFLINE"
#define kFUNCTION_HAVE_ANGLE_SETTING @"FUNCTION_HAVE_ANGLE_SETTING"
#define kFUNCTION_IS_MULTI_UPLOAD @"FUNCTION_IS_MULTI_UPLOAD"
#define kFUNCTION_HAVE_SELF_UPDATE @"FUNCTION_HAVE_SELF_UPDATE"
#define kFUNCTION_HAVE_HSD @"FUNCTION_HAVE_HSD"





@end
